// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	// Unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

var calculatorSumStreamDesc = &grpc.StreamDesc{
	StreamName: "Sum",
}

func (c *calculatorClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorService is the service API for Calculator service.
// Fields should be assigned to their respective handler implementations only before
// RegisterCalculatorService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type CalculatorService struct {
	// Unary
	Sum func(context.Context, *SumRequest) (*SumResponse, error)
}

func (s *CalculatorService) sum(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/calculator.Calculator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterCalculatorService registers a service implementation with a gRPC server.
func RegisterCalculatorService(s grpc.ServiceRegistrar, srv *CalculatorService) {
	srvCopy := *srv
	if srvCopy.Sum == nil {
		srvCopy.Sum = func(context.Context, *SumRequest) (*SumResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "calculator.Calculator",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Sum",
				Handler:    srvCopy.sum,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "calculator.proto",
	}

	s.RegisterService(&sd, nil)
}
